### PR TITLE
Remove refrences to sharat87/autoenv

### PR DESCRIPTION
**Pull request by bb010g**
It could be misleading to those wanting to use autoenv if they just decide to pull down your fork without too much examination and don't check to see that your fork has already been ~~merged~~ closed (I can't read!) ([kennethreitz/autoenv#39](https://github.com/kennethreitz/autoenv/pull/39)) and that much more work has been put into the main repo.

### CODE REVIEW

**Comment by bb010g** [comment]
What do you all think of putting in a link to [Tarrasch/zsh-autoenv](https://github.com/Tarrasch/zsh-autoenv) instead? It contains the fix from sharat87/autoenv and is zsh-optomized.

**Comment by sharat87** [comment]
I suppose removing the link to my fork is a good step. But I'm not sure if we should link to the original repo or @Tarrasch's fork. What do you think we should do @Tarrasch?

**Comment by Tarrasch** [comment]
I think it makes more sense pointing to the zsh-optimized version. Mine isn't really a fork but a rewrite. Now mostly contributed to by @blueyed.

So yes, please fork to Tarrasch/zsh-autoenv I think. :)

**Comment by sharat87** [comment]
Cool. Lets do that.

@bb010g, I just noticed that the changes you made are to the `gh-pages` branch. The contents of that branch will be overwritten with the README file. I'm closing this pull request and make the change to the README file.

Thank you!

**Comment by sharat87** [comment]
Relevant commit: ad8cfa9

**Pull request closed without merging**
