### PR TITLE
Change default directory to comply to XDG standard

### PR DESCRIPTION
**Pull request by Abdillah**
As a user, I want all software to comply to XDG. Thus, in the future my home dir will be more clean and organized.

### CODE REVIEW

**Comment by desyncr** [comment]
While I like XDG to keep an uncluttered home dir you can configure it without problem by setting up ADOTDIR=$XDG_CONFIG_DIR/antigen

**Comment by desyncr** [comment]
@Abdillah Regardless of what I said above, I think we should add a check for old-style antigen configuration direction (~/.antigen) otherwise after updating users may lose their configurations.

**Comment by ryneeverett** [comment]
This doesn't strike me as correct. `~/.antigen` doesn't contain any *configuration* AFAIK.

**Comment by desyncr** [comment]
By default it does contains the revert-info plus the checkout bundles.

I'll leave this out on hold for now as it's not a priority right now.

Thank you for contributing to antigen.

**Comment by ryneeverett** [comment]
> By default it does contains the revert-info plus the checkout bundles.

That is not *configuration*. If you were going to follow XDG you might put it in `$XDG_DATA_HOME` but I agree that it's not a priority.

**Comment by desyncr** [comment]
>That is not configuration. If you were going to follow XDG you might put it in $XDG_DATA_HOME but I agree that it's not a priority.

Granted but it's data we should take into account if we integrate this change IMO.

**Pull request closed without merging**
