### PR TITLE
Improve overall plugins load performance

### PR DESCRIPTION
**Pull request by outcoldman**
-antigen-parse-args is very expensive. Avoiding using it in internal calls improve overall performance.
Instead of using -antigen-parse-args just invoke functions with arguments in expected order.

I got 50% performance improvement.

### CODE REVIEW

**Comment by outcoldman** [comment]
Just a note, another way to get 50% improvement is to avoid using `-antigen-parse-args` at all. For example in my own `.zshrc` I specified function right after `source ./antigen/antigen.zsh`

```
    antigen-fbundle() {
        local loc=$1
        local url=${2:-$ANTIGEN_DEFAULT_REPO_URL}
        local make_local_clone=${3:-true}
        if $make_local_clone; then
            -antigen-ensure-repo $url
        fi
        -antigen-load "$url" "$loc" "$make_local_clone"
    }
```

After that I use simplified syntax of

```

    # antigen use oh-my-zsh
    antigen-fbundle lib

    antigen-fbundle plugins/bower
    #... other plugins

    # load from url
    antigen-fbundle / https://github.com/Tarrasch/zsh-autoenv.git

    # load from local locations (my own plugins)
    antigen-fbundle / ./plugins/aliases false
    
    # Load plugin
    antigen-fbundle powerlevel9k.zsh-theme https://github.com/bhilburn/powerlevel9k.git

    antigen apply
```

**Comment by desyncr** [comment]
I think they'll like to keep the old syntax. Regardless of that it's an alternative to the whole cache thing at https://github.com/zsh-users/antigen/pull/129. I'll try this later today.

**Comment by outcoldman** [comment]
@desyncr sure, it make sense, I don't want to change the syntax, this is why I just mentioned that it can be another way to improve performance. 

This pull request is only about avoiding unnecessary using `-antigen-parse-args` in internal calls.

We definitely need to fix `-antigen-parse-args`, as it makes antigen load in 4x times slower. As a proposal we can make it less generic and work only for `antigen bundle` (including all other alternatives, like `use` or `theme`).

**Comment by forivall** [comment]
Just remember, desyncr isn't a contributor to antigen at all. I have a fixed version of antigen parse args #132, but abandoned it because the maintainers seem to be absent, so I just switched to zgen.

**Comment by outcoldman** [comment]
@forivall looking on the history of commits it seems like that original maintainer @sharat87 is looking on patches once in a month, so we just need to have a little bit of patience. Could you reopen your pull request as it can be very useful for all antigen users.

**Comment by desyncr** [comment]
Thank you @outcoldman for these changes. It has been [merged](https://github.com/zsh-users/antigen/commit/c5012ebe73696fb16743a223aa4d1dfd8b0fba52).

**Pull request closed without merging**
