### PR TITLE
Add feature to list all bundle absolute paths

### PR DESCRIPTION
**Pull request by knakayama**
Sometimes I want to get my local bundle paths, for example:

* tweaking some codes
* [peco style](https://github.com/peco/peco) directory moving

So I add this feature. I think useful feature for some people.

### CODE REVIEW

**Comment by desyncr** [comment]
Works perfectly. :+1: 

Not sure if it make sense to merge it though, as it doesn't seem to serve the same purpose the 'list' command was thought for (ie, it's missing all the [described](https://github.com/knakayama/antigen/commit/8ed1350cb13544b50103178e46b32a0a639f5678#diff-dca1c539c67ad53448067afbc3e37273L335) columns).

May be a 'path' argument and a second 'raw' argument to strip the extra columns?:


    antigen list # => '<repo-url> <loc> <btype> <has-local-clone?>'
    antigen list --raw # => '<repo-url>'

    antigen list --path # => '<path> <loc> <btype> <has-local-clone?>'
    antigen list --path --raw # => '<path>'

What you think? Makes any sense to you?

**Comment by knakayama** [comment]
Sorry for my poor English.

> Not sure if it make sense to merge it though, as it doesn't seem to serve the same purpose the 'list' command was thought for 

I think the purpose is responsible for **the list subcommand itself**, not the option to the subcommand. It makes sense that the original meanings can be changed by the option, to me. Is it just me only? I can't explain properly, but I can see the statement **list path** is a **native English**.
Well, I have another approach, adding path subcommand. But there is a minus point. It is too exaggerative ;)

**Comment by knakayama** [comment]
@desyncr 
Thanks for your review. I decide to create [zsh plugin](https://github.com/knakayama/antigen-bundle-record-moving) for this purpose, so I close this PR.

**Comment by desyncr** [comment]
Good idea to move it into a plugin. Wish there were a way to extend antigen without having to hack into antigen itself, some thing such as extensions or similar. Something to think about.

**Pull request closed without merging**
