### PR TITLE
fix $fpath some time has double slash ending

### PR DESCRIPTION
**Pull request by bolasblack**
For example:

    /Users/user/.antigen/repos/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-syntax-highlighting.git//

### CODE REVIEW

**Comment by desyncr** [comment]
`loc` is an argument that defaults to "/" and it can naturally be overwritten. So, removing it will break things.

If you feel the need to remove the extra slash then you should check if the value is "/" and if it isn't then append it, otherwise do not:

     if [ "$loc" == "/" ]; then
         loc=""
     fi

     if $make_local_clone; then
         location="$(-antigen-get-clone-dir "$url")/$loc"
     else
         location="$url/$loc"
     fi

**Comment by bolasblack** [comment]
@desyncr 

* Your idea is

      empty the `$loc` if it is a slash, then append it to `$location`

* My idea is

      if the `$loc` is a slash, then do not append it to `$location`


I think we will get the same result, isn't it? :)

**Comment by desyncr** [comment]
Oh, yeah, my bad. For some reason I didn't saw line 268 :+1:

**Comment by sharat87** [comment]
Thank you and sorry for the delay :)

**Comment by bolasblack** [comment]
@sharat87 :)

**Pull request merged**
